In [1]:
#Importing the libraries  
import numpy as np 
import pandas as pd  

In [2]:
# Importing the data
data= pd.read_csv('Social_Network_Ads.csv')

In [3]:
#taking look at data
data.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [4]:
#Extract the columns
x = data.iloc[:,2:4].values
y = data.iloc[:,-1].values
#Reshape 1-D array to 2-D array
y = y.reshape(len(y),1)

In [5]:
#Perform Feature Scaling on features
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x = sc.fit_transform(x)
x

array([[-1.78179743, -1.49004624],
       [-0.25358736, -1.46068138],
       [-1.11320552, -0.78528968],
       [-1.01769239, -0.37418169],
       [-1.78179743,  0.18375059],
       [-1.01769239, -0.34481683],
       [-1.01769239,  0.41866944],
       [-0.54012675,  2.35674998],
       [-1.20871865, -1.07893824],
       [-0.25358736, -0.13926283],
       [-1.11320552,  0.30121002],
       [-1.11320552, -0.52100597],
       [-1.6862843 ,  0.47739916],
       [-0.54012675, -1.51941109],
       [-1.87731056,  0.35993973],
       [-0.82666613,  0.30121002],
       [ 0.89257019, -1.3138571 ],
       [ 0.70154394, -1.28449224],
       [ 0.79705706, -1.22576253],
       [ 0.98808332, -1.19639767],
       [ 0.70154394, -1.40195167],
       [ 0.89257019, -0.60910054],
       [ 0.98808332, -0.84401939],
       [ 0.70154394, -1.40195167],
       [ 0.79705706, -1.37258681],
       [ 0.89257019, -1.46068138],
       [ 1.08359645, -1.22576253],
       [ 0.89257019, -1.16703281],
       [-0.82666613,

In [6]:
#Combine features and target into a single 2-D array
X = np.hstack((x,y))
X

array([[-1.78179743, -1.49004624,  0.        ],
       [-0.25358736, -1.46068138,  0.        ],
       [-1.11320552, -0.78528968,  0.        ],
       ...,
       [ 1.17910958, -1.46068138,  1.        ],
       [-0.15807423, -1.07893824,  0.        ],
       [ 1.08359645, -0.99084367,  1.        ]])

In [7]:
#Split the data into training and testing samples 
from sklearn.model_selection import train_test_split
train_data,test_data = train_test_split(X,test_size = 0.2,random_state=42)

In [8]:
#Take a look at size of training samples
train_data.shape

(320, 3)

In [9]:
#Take a look at size of testing samples
test_data.shape

(80, 3)

In [10]:
#Split the dataset by classvalues,returns a dictionary
def seperate_byclass(data):
    dict = {}
    for i in range(len(data)):
        arr = data[i]
        class_name = arr[-1]
        if class_name not in dict:
            dict[class_name] = []
        dict[class_name].append(arr)
    return dict

In [11]:
seperate_byclass(X)

{0.0: [array([-1.78179743, -1.49004624,  0.        ]),
  array([-0.25358736, -1.46068138,  0.        ]),
  array([-1.11320552, -0.78528968,  0.        ]),
  array([-1.01769239, -0.37418169,  0.        ]),
  array([-1.78179743,  0.18375059,  0.        ]),
  array([-1.01769239, -0.34481683,  0.        ]),
  array([-1.01769239,  0.41866944,  0.        ]),
  array([-1.20871865, -1.07893824,  0.        ]),
  array([-0.25358736, -0.13926283,  0.        ]),
  array([-1.11320552,  0.30121002,  0.        ]),
  array([-1.11320552, -0.52100597,  0.        ]),
  array([-1.6862843 ,  0.47739916,  0.        ]),
  array([-0.54012675, -1.51941109,  0.        ]),
  array([-1.87731056,  0.35993973,  0.        ]),
  array([-0.82666613,  0.30121002,  0.        ]),
  array([-0.82666613, -0.78528968,  0.        ]),
  array([-0.63563988, -1.51941109,  0.        ]),
  array([-0.63563988,  0.12502088,  0.        ]),
  array([-1.59077117, -1.5781408 ,  0.        ]),
  array([-0.92217926, -0.75592482,  0.       

In [12]:
#Calculate the mean for a list of numbers
def mean(num):
    return np.mean(num)

In [13]:
#calculate standard deviation for a list of numbers
def standard_deviation(num):
    return np.std(num)

In [14]:
#calculate mean,standard deviation and count for each column in dataset
def MeanAndStdDev(data):
    tuples = []
    for column in zip(*data):
        tuples.append([mean(column),standard_deviation(column),len(column)])
    del tuples[-1]
    return tuples

In [15]:
#Find Mean,standard deviation under each class
def MeanAndStdDev_forClass(data):
    dict = seperate_byclass(data)
    info = {}
    for classvalue,instances in dict.items():
        info[classvalue] = MeanAndStdDev(instances)
    return info

In [16]:
#Calculate Gaussian Probability Density function
from math import pi
from math import exp
def calculate_probability(x,mean,stdev):
    expo = exp(-(x-mean)**2/2*stdev**2)
    return (1/(np.sqrt(2*pi))*stdev)*expo

In [17]:
#Calculate the class probabilties
def probability_forClass(info,test):
    probabilities = {}
    total_rows =0
    for classvalue in info:
        total_rows += info[classvalue][0][2]
    for classvalue,classsummaries in info.items():
        probabilities[classvalue] = info[classvalue][0][2]/float(total_rows)
        for i in range(len(classsummaries)):
            mean,stdev,count = classsummaries[i]
            probabilities[classvalue] *= calculate_probability(test[i],mean,stdev)
    return probabilities

In [18]:
#Make prediction - Highest probability is the prediction
def predict(info,test):
    probabilities = probability_forClass(info,test)
    bestlabel = None
    bestproba = -1
    for classvalue,probability in probabilities.items():
        if bestlabel is None or probability > bestproba:
            bestproba = probability
            bestlabel = classvalue
    return bestlabel

In [19]:
#Returns predictions for a set of data
def getPrediction(info,test):
    predictions = []
    for i in range(len(test)):
        result = predict(info,test[i])
        predictions.append(result)
    return predictions

In [20]:
#prepare the model
info = MeanAndStdDev_forClass(train_data)

In [21]:
#test model
predictions = getPrediction(info,test_data)

In [22]:
#Actual values
test_data[:,-1]

array([0., 1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.,
       0., 0., 1., 0., 0., 1., 1., 0., 1., 0., 0., 1., 0., 1., 0., 1., 0.,
       1., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
       1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 1.,
       0., 0., 1., 0., 0., 0., 1., 0., 1., 1., 0., 1.])

In [23]:
#Predicted values
predictions = np.array(predictions)
predictions

array([0., 1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0.,
       1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1.,
       0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0.])

In [24]:
#Accuracy Score
def accuracy(test_data,predictions):
    correct = 0
    for i in range(len(test_data)):
        if(test_data[i][-1] == predictions[i]):
            correct +=1
    return (correct/len(test_data))*100

In [25]:
#Check the accuracy of the model
accuracy(test_data,predictions)

81.25